#!/usr/bin/env bash
#
# wechat-proxy-setup.sh
# 在 VPS 上一次跑完：装 nginx + certbot + 配反代 + 拿 Let's Encrypt 证书
#
# 用法：
#   1. 把这个脚本 scp 到 VPS：
#        scp scripts/wechat-proxy-setup.sh user@your-vps:/tmp/
#   2. ssh 上去用 root 跑：
#        sudo bash /tmp/wechat-proxy-setup.sh
#   3. 按提示填域名 + 邮箱 + token
#
# 跑完后：
#   - https://你的域名/wechat/cgi-bin/token?...  会代理到 api.weixin.qq.com
#   - 必须带 X-Auth-Token: <token> header，否则 401
#   - VPS 公网 IP 加到公众号后台白名单一次
#
set -euo pipefail

# ============== 1. 收集参数 ==============
read -rp "域名（指向这台 VPS 的，比如 wechat-proxy.yourdomain.com）: " DOMAIN
read -rp "邮箱（Let's Encrypt 通知用）: " EMAIL
read -rp "鉴权 token（自己随便写一串，至少 32 位推荐 openssl rand -hex 32 生成）: " AUTH_TOKEN

if [[ -z "$DOMAIN" || -z "$EMAIL" || -z "$AUTH_TOKEN" ]]; then
  echo "三个参数都必填，退出。"
  exit 1
fi

# ============== 2. 装包 ==============
echo "==> 装 nginx + certbot ..."
if command -v apt >/dev/null; then
  apt update -qq
  apt install -y nginx certbot python3-certbot-nginx curl
elif command -v yum >/dev/null; then
  yum install -y epel-release
  yum install -y nginx certbot python3-certbot-nginx curl
else
  echo "未识别的发行版，自己装 nginx + certbot 吧。"
  exit 1
fi

# ============== 3. 写 nginx 第一阶段配置（仅 80） ==============
# 阶段一只配 80 server，让 certbot 走 webroot 验证拿证书
# 阶段二（拿到证书后）追加 443 server 和反代规则

NGINX_CONF="/etc/nginx/sites-available/wechat-proxy.conf"
[[ -d /etc/nginx/sites-available ]] || mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled

# 确保 webroot 目录存在
mkdir -p /var/www/html

echo "==> 写 nginx 阶段一配置（仅 80） → $NGINX_CONF ..."
cat > "$NGINX_CONF" <<NGINX
# WeChat Official Account API reverse proxy (Stage 1: HTTP only)
# Generated by wechat-proxy-setup.sh

server {
    listen 80;
    server_name $DOMAIN;

    # certbot webroot 验证
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # 其他先 200，等证书到位后阶段二会加 https 重定向
    location / {
        return 200 "wechat-proxy: pending https setup\n";
        add_header Content-Type text/plain;
    }
}
NGINX

ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/wechat-proxy.conf

# 删默认站点（如果存在），避免 default_server 抢域名
[[ -L /etc/nginx/sites-enabled/default ]] && rm /etc/nginx/sites-enabled/default

# Debian/Ubuntu 的 nginx.conf 默认 include sites-enabled，CentOS 不一定，确保一下
if ! grep -q "sites-enabled" /etc/nginx/nginx.conf 2>/dev/null; then
  sed -i '/include \/etc\/nginx\/conf.d\/\*.conf;/a\    include /etc/nginx/sites-enabled/*;' /etc/nginx/nginx.conf || true
fi

# 测试语法
nginx -t

# ============== 4. 启动 nginx ==============
systemctl enable nginx
systemctl restart nginx
echo "==> nginx 阶段一启动完成（仅 HTTP 80）"

# ============== 5. 拿 SSL 证书 ==============
echo "==> 用 certbot webroot 模式拿 Let's Encrypt 证书 ..."
certbot certonly --webroot -w /var/www/html -d "$DOMAIN" \
  --email "$EMAIL" --agree-tos --non-interactive

# 自动续期 dry-run 测一下
certbot renew --dry-run

# ============== 6. 写 nginx 阶段二配置（80 + 443 + 反代） ==============
echo "==> 拿到证书，写 nginx 阶段二配置（加 443 + 反代） → $NGINX_CONF ..."
cat > "$NGINX_CONF" <<NGINX
# WeChat Official Account API reverse proxy (Stage 2: HTTPS + reverse proxy)
# Generated by wechat-proxy-setup.sh

server {
    listen 80;
    server_name $DOMAIN;

    # 续期时 certbot 还会用 webroot 验证
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    # 其他全部跳 https
    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name $DOMAIN;

    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

    # 现代 SSL 配置
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers off;

    # 安全 header
    add_header Strict-Transport-Security "max-age=31536000" always;

    # 默认拒绝所有路径，只放行 /wechat/
    location / {
        return 404;
    }

    # 反代 /wechat/ → https://api.weixin.qq.com/
    # 例：本地脚本调 https://$DOMAIN/wechat/cgi-bin/draft/add?access_token=XXX
    #     → 实际打到 https://api.weixin.qq.com/cgi-bin/draft/add?access_token=XXX
    location /wechat/ {
        # 鉴权：必须带 X-Auth-Token header
        if (\$http_x_auth_token != "$AUTH_TOKEN") {
            return 401;
        }

        # 反代到微信
        proxy_pass https://api.weixin.qq.com/;
        proxy_ssl_server_name on;
        proxy_ssl_name api.weixin.qq.com;
        proxy_set_header Host api.weixin.qq.com;
        proxy_set_header X-Real-IP \$remote_addr;

        # 大文件上传（永久素材最大 64MB）+ 长超时
        client_max_body_size 64m;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }

    # 健康检查端点（不需要 token，给本地脚本测试用）
    location = /health {
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}
NGINX

# 测试 + 重启
nginx -t
systemctl reload nginx
echo "==> nginx 阶段二启动完成（HTTPS 反代就绪）"

# ============== 6. 出口 IP + 验证 ==============
EGRESS_IP=$(curl -s ifconfig.me)
echo ""
echo "============================================================"
echo "✅ 装完了"
echo "============================================================"
echo ""
echo "🌐 你的代理域名：https://$DOMAIN"
echo "📌 VPS 出口 IP（加到公众号白名单的就是这个）：$EGRESS_IP"
echo "🔑 鉴权 token（本地脚本要带）：$AUTH_TOKEN"
echo ""
echo "下一步："
echo "  1. 去 https://mp.weixin.qq.com → 开发 → 基本配置 → IP 白名单"
echo "     把 $EGRESS_IP 加进去"
echo ""
echo "  2. 本地测试代理是否通："
echo "     curl https://$DOMAIN/health    # 应该返回 ok"
echo ""
echo "  3. 测试微信 API（先确认你已经把 IP 加到白名单了）："
echo "     curl -H 'X-Auth-Token: $AUTH_TOKEN' \\"
echo "       'https://$DOMAIN/wechat/cgi-bin/token?grant_type=client_credential&appid=YOUR_APPID&secret=YOUR_SECRET'"
echo ""
echo "  4. 在本地 .baoyu-skills/.env 加："
echo "     WECHAT_API_BASE=https://$DOMAIN/wechat"
echo "     WECHAT_API_TOKEN=$AUTH_TOKEN"
echo ""
echo "============================================================"
